# Generated by Django 4.1.1 on 2022-09-29 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ویژگی')),
                ('default', models.PositiveIntegerField(default=0, verbose_name='امتیاز پیش\u200cفرض')),
                ('zarib', models.PositiveIntegerField(default=0, verbose_name='ضریب')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی',
            },
        ),
        migrations.CreateModel(
            name='Train_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مکان')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان',
            },
        ),
        migrations.CreateModel(
            name='Train_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='جامعه هدف')),
            ],
            options={
                'verbose_name': 'مخاطبین',
                'verbose_name_plural': 'مخاطبین',
            },
        ),
        migrations.CreateModel(
            name='Train_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'نوع تمرین',
                'verbose_name_plural': 'نوع تمرین',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='زمان')),
                ('category', models.ManyToManyField(to='App.train_type', verbose_name='دسته\u200cبندی تمرین')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.train_location', verbose_name='مکان')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.train_target', verbose_name='جامعه هدف')),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': 'تمرین',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.feature', verbose_name='ویژگی')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='بازیکن')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.train', verbose_name='تمرین')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیاز',
            },
        ),
    ]
