# Generated by Django 4.1.1 on 2022-09-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='feature',
        ),
        migrations.AddField(
            model_name='point',
            name='feature',
            field=models.ManyToManyField(to='App.feature', verbose_name='ویژگی'),
        ),
    ]
