# Generated by Django 4.1.1 on 2022-09-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_point_player_remove_point_train_point_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='train',
        ),
        migrations.AddField(
            model_name='point',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App.train', verbose_name='تمرین'),
        ),
    ]
